### ISSUE TITLE
Bug in Filemin File Manager Module

### ISSUE THREAD

**Issue by gderf** [Real-Gecko/Filemin#66] opened 2015-09-18 13:20 UTC
Webmin Version 1.763 on Debian Wheezy with Chrome browser on Windows 7.

If a folder name contains an apostrophe ( ' ), clicking on the folder to enter it fails with the following error:

Following errors occured while performing operation
Error opening directory /media/41991950-4d12-4475-86b8-ba54ec09323b/multimedia-content-d1/movies/Example's No such file or directory

Changing the offending apostrophe to a backtic ( ` ) is a good workaround.

**Comment by Real-Gecko** [comment] 2015-09-20 11:18
There were some trouble of transferring HTML specific symbols in file/folder names. I'll look into it.
By now try updating to the latest Filemin version manually, it has some patches after Webmin dev release.

**Comment by gderf** [comment] 2015-09-20 13:06
Thanks for the reply. I manually installed filemin-0.9.6.linux.wbm.gz, but the problem remains.

**Comment by iliaross** [comment] 2015-09-20 13:18
You could experience cache issue. Try restarting Webmin..

**Comment by gderf** [comment] 2015-09-20 13:34
Thanks for the suggestion, but no joy.

**Comment by berntkau** [comment] 2015-09-23 08:03
Hi! I hope I'm not messing up the subject, but I've had a, maybe connecting, problem with scandinavian characters in file and folder names. They simply don't show and I get the following error message:
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.760 Date: Wed, 23 Sep 2015 07:20:35 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
utf8 "\xE4" does not map to Unicode at /usr/lib/perl/5.14/Encode.pm line 174.
Is this a problem with Filemin or a browser setting issue? 

Ubuntu 12.04 Server LTS,  Win Vista x64 and Chrome browser latest version.

PS I really appreciate the Filemin. And despite the problem It is a great help! Thank You.

**Comment by iliaross** [comment] 2015-09-23 08:10
@berntkau I just think you need to make sure that you change language to UTF8 in `Webmin->Webmin Configuration->Language`. Make sure that `Webmin->Language and Theme` module doesn't override your global settings.

**Comment by berntkau** [comment] 2015-09-23 09:35
@qooob Thank you for your very quick respons. I changed the encoding to utf-8 in Webmin and then also in Chrome but no luck. Same error message keeps popping up. There is no hurry, but I hope a solution will be found.

**Comment by Real-Gecko** [comment] 2015-11-06 12:40
I think it was caused by &urlize function, the same thing caused non ASCII file/folder names unusable.
After I removed urlize function from Filemin I can create folders with apostrophe in name.
I'm closing issue right now, changes will be in version 0.9.7.
Feel free to reopen issue if you encounter it after new release.

**Closed as completed by Real-Gecko** 2015-11-06 12:40 UTC

**Comment by gderf** [comment] 2015-11-06 14:19
Thanks, I'll let you know.
