### ISSUE TITLE
Directory showing as download

### ISSUE THREAD

**Issue by Doemela** [Real-Gecko/Filemin#25] opened 2015-07-15 23:02 UTC
On Ubuntu Linux 14.04, Webmin version 1.760
The directory's /dev /home and /boot show as files to download (https://uri:10000/filemin/download.cgi?file=home&path=)
If I do this in new tab https://uri:10000/filemin/index.cgi?path=/home it works user is root.

Thanks for your work +9000 times better than file manager

**Comment by bronzeblood** [comment] 2015-07-16 02:54
Im getting similar problems , it seems directory's that are mount points want to download instead of opening when you click them. 

Type -  inode-directory  - opens fine 
Type -      inode-mount-point - want to download a file instead of opening .

Hope this helps ,

**Comment by Real-Gecko** [comment] 2015-07-16 04:36
Duplicate of #20

**Closed as completed by Real-Gecko** 2015-07-16 04:36 UTC
Labels: duplicate
