### ISSUE TITLE
Very bad bug. IMPORTANT

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#54] opened 2015-08-26 14:55 UTC
There is a problem with copy CMS websites, eg. Magento...

Please have a look my screen-video to learn more.

http://screencast-o-matic.com/watch/cojO2MfkgD

**Comment by singhdd93** [comment] 2015-08-26 18:44
webmin/webmin#245

**Comment by Real-Gecko** [comment] 2015-08-26 22:52
Tis not a bug, tis a feature xD
I'll fix that today.

**Comment by Real-Gecko** [comment] 2015-08-27 00:11
Fixed in 0.9.6

**Closed as completed by Real-Gecko** 2015-08-27 00:11 UTC
