### ISSUE TITLE
chown.cgi returns nothing for unexisting user 

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#45] opened 2015-08-22 20:00 UTC
If you have some files/folders that are not own by a user that is on the system you simply get `:` in permission field:

![screenshot from 2015-08-22 22-58-14](https://cloud.githubusercontent.com/assets/4426533/9425670/7e66fd8a-4921-11e5-8a71-a28fa1c34e6f.png)

However if you do `ls -lsa` in terminal you get numerical values, like `1000:1000`. I think its worth to keep same practice in Filemin!

**Comment by Real-Gecko** [comment] 2015-08-23 16:04
If you just extracted the archive then it is duplicate of #9

**Closed as completed** 2015-11-06 09:23 UTC
