### ISSUE TITLE
Error Paste

### ISSUE THREAD

**Issue by Geant200** [Real-Gecko/Filemin#136] opened 2017-08-19 21:54 UTC
Hello I encounter a problem when I want to make a copy paste it mark me Error paste that its for a file or a folder.

I just uninstalled Filemin and Filemine Update completely and I reinstall the latest version it's the same.

Install versions
Debian 9.1
Filemin [2.1.0] - 2016-10-20
Filemin Update v2.0.0
Usermin 1.710
Webmin 1.851
Virtualmin 6.00
Authentic Theme 18.49-9

How can I fix the problem ??.

Thank you in advance.

**Comment by Real-Gecko** [comment] 2018-01-29 07:29
Duplicate of #135

**Closed as completed by Real-Gecko** 2018-01-29 07:29 UTC
